some changes
* unmerged gimp and vlc
* added back the /etc/hosts generation suite
* auto-remove ticuhost when rsync-ing
* not using bindist USE flag anymore
* .bashrc nolonger save to history commands beginning with space (so
chdir-ing in folders from mc isn't saved anymore)
* using an image with stars as desktop wallpaper
* failed attempt to make xfdesktop show desktop icons, instead of just
minimized windows or no icons at all (works in manjaro tho)
* changed theme to show restore-button icon properly when maximized
* compress=no for btrfs has no effect in fstab (it defaults to no option
which means zlib)
* firefox without gstreamer and hwaccel USE flags

diff --git a/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit b/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
--- a/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
+++ b/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
@@ -74,4 +74,11 @@ cat ./net ./nftables.rules | grep --color=always -E -- "(192|redacted)"
 popd
 echo "--"
 
+echo "-- removing ticuhost"
+pushd "${destdir}/gentoo/etc/" || echo "FAIL!"
+sed -i ./hosts -re 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+.*ticuhost.*$//g'
+cat ./hosts | grep --color=always -- 'ticuhost'
+popd
+echo "--"
+
 echo "All done."
