bunch of fixes and updates
* To avoid crashes while watching youtube videos, removed firefox USE flag: system-libvpx (no more crashes; been days)
* removed a bunch of fonts (all manually installed ones, I think)
* adjtime clock updated
* bash's etc bashrc got updated (by them)
* certs got updated
* new net IPs in net and nft rules (you can't see IPs, unless they leaked)
* relaxed /etc/hosts for google, twitter, firefox addons updates, safe browsing,
* inittab got updated to use openrc instead of rc as executable
* some mc updates (by emerge)
* portage log dir (via PORT_LOGDIR) set to /tmp because of the imense number of writes(with sync, apparently?), I've already done 4 terabytes(in writes)!!(how in teh!)
* leftover wine configs for portage
* vlc can't see periscope .mp4 files as it stand now
* media-libs/openh264 could supposedly(probably not tho) install firefox's Cisco Systems openh264 plugin, but now with USE=-plugin it's for sure not going to!
* set vlc output to something that apparently doesn't crash my radeon driver (hasn't yet anyway)
* disabled ffmpeg generating those .log files everytime I was running youtube-dl
* auto install(in firefox) fix for https-everywhere (it was installing the same old version!) + auto pull on ./go (which wasn't present before)
* changed terminal font to an available equivalent one
* changed background to different star-like or water-like black/blue wallpaper
* removed Ctrl+Alt+d shortcut for launching terminal due to X stalling for a few(10-30) seconds while using 100% cpu(seen in top) - this is the same issue that Windows 98/xp used to have! how odd is that! But this issue didn't happen, say like 1 month ago. So it's a regression, or some setting(s) I've changed.
* update .gitconfig with current credentials
* set permanent MAC via arp -s
* also remove the MAC from rsync backup, so it's not backed up on git (for some reason, hmm)
* add all 3 kernels in portage world (aka favs)
* link from kernel cpu undervolting patch to github location
* get keepassx back
* removed lxde-base/lxmenu-data mpg123, schismtracker
* get gimp back, vlc, net-misc/youtube-dl
* got net-ftp/tftp-hpa
* removed x11-apps/radeontop
* add the public ssh key
* a rust.vim note (rme.txt) to keep the symlink in sync
* disable a vlc patch due to already fixed by upstream
* update year in root readme
* removed second panel
* fonts removed:
25-ttf-arphic-ukai-render.conf
25-ttf-arphic-uming-bitmaps.conf
25-ttf-arphic-uming-render.conf
35-ttf-arphic-ukai-aliases.conf
35-ttf-arphic-uming-aliases.conf
41-ttf-arphic-ukai.conf
41-ttf-arphic-uming.conf
43-wqy-zenhei-sharp.conf
44-wqy-zenhei.conf
59-google-droid-sans.conf
59-google-droid-sans-mono.conf
59-google-droid-serif.conf
64-ttf-arphic-uming.conf
66-ja-ipafonts.conf
66-takao-fonts.conf
75-ttf-arphic-ukai-select.conf
90-ttf-arphic-ukai-embolden.conf
90-ttf-arphic-uming-embolden.conf

diff --git a/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit b/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
--- a/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
+++ b/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/rsync/4copytogit
@@ -81,4 +81,12 @@ cat ./hosts | grep --color=always -- 'ticuhost'
 popd
 echo "--"
 
+echo "-- removing permmac"
+pushd "${destdir}/gentoo/etc/local.d/" || echo "FAIL!"
+thisarpfn='./010_arp.start'
+sed -i "$thisarpfn" -re 's/[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]/xx:xx:xx:xx:xx:xx/g'
+cat "$thisarpfn" | grep --color=always -E -- "[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]" && echo "FAIL!!" #FIXME: need the whole script to fail! don't just echo it!, also above ^
+popd
+echo "--"
+
 echo "All done."
