sysupdate & stuff
* remove dhcpcd
* fix ssdwritten when ./rsync/4...
* disabled close port 8081 script
* updated some(not all) from *.pacnew files
* ignore firefox&chromium packages from pacman -Syu
* try sde1 fir nspro duo card
* utc bandwidth update
* timezone update
* updated picocom with logfile feature
* redacting IP in firewall rules
* removing more packages

diff --git a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/rsync/4copytogit b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/rsync/4copytogit
--- a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/rsync/4copytogit
+++ b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/rsync/4copytogit
@@ -69,13 +69,13 @@ if test -d "${src}/etc/ssl/certs/"; then
   popd
 fi
 
-#echo "-- redacting local IP"
-#pushd "${src}/etc/conf.d/" || echo "FAIL!"
-#sed -i ./net -re 's/192\.168\.[0-9]+\.[0-9]+/192.168.redacted.redacted/g'
+echo "-- redacting local IP"
+pushd "${src}/etc/iptables/" || echo "FAIL!"
+sed -i ./myrules.v4 -re 's/192\.168\.[0-9]+\.[0-9]+/192.168.redacted.redacted/g'
 #sed -i ./nftables.rules -re 's/192\.168\.[0-9]+\.[0-9]+/192.168.redacted.redacted/g'
-#cat ./net ./nftables.rules | grep --color=always -E -- "(192|redacted)"
-#popd
-#echo "--"
+cat ./net ./nftables.rules | grep --color=always -E -- "(192|redacted)"
+popd
+echo "--"
 
 echo "-- removing ticuhost"
 pushd "${src}/etc/" || echo "FAIL!"
