much compile

diff --git a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/bin/_rustic_helper_script b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/bin/_rustic_helper_script
--- a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/bin/_rustic_helper_script
+++ b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/bin/_rustic_helper_script
@@ -29,6 +29,6 @@ for i in "${searchdirs[@]}"; do
   fi
 done
 
-echo "!! not found '$fname' in search any of dirs: '${searchdirs[@]}'"
+echo "!! not found '$fname' in search any of dirs: '${searchdirs[@]}'" >&2
 
 
