after x11-drivers/xf86-video-virtualbox
lots of other stuff got fixed also
compilation continues

diff --git a/system/Z575/OSes/gentoo/filesystem_now/gentoo/etc/portage/postsync.d/1repatch b/system/Z575/OSes/gentoo/filesystem_now/gentoo/etc/portage/postsync.d/1repatch
--- a/system/Z575/OSes/gentoo/filesystem_now/gentoo/etc/portage/postsync.d/1repatch
+++ b/system/Z575/OSes/gentoo/filesystem_now/gentoo/etc/portage/postsync.d/1repatch
@@ -6,6 +6,10 @@ pushd /
 for i in /home/zazdxscf/patches/webrsync/*.patch ; do 
   #patch -Np1 -i /home/zazdxscf/patches/webrsync/notify_when_patches_folder_inaccessible_by_portage.patch
   patch -Np1 -i "$i"
+  ec="$?"
+  if test "$ec" -ne "0"; then
+    echo "FAILED!" | grep --color=tty "FAIL"
+  fi
 done
 )
 popd
