chromium-dev-git PKGBUILD is such a huge mess
i don't really want to do the merging

diff --git a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/build/1packages/chromium-dev-git/PKGBUILD b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/build/1packages/chromium-dev-git/PKGBUILD
--- a/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/build/1packages/chromium-dev-git/PKGBUILD
+++ b/system/Z575/OSes/manjaro2/on_baremetal/filesystem_now/manjaro/home/z/build/1packages/chromium-dev-git/PKGBUILD
@@ -10,7 +10,7 @@
 #########################
 
 _use_clang=1           # Use clang compiler (system). Results in faster build and smaller chromium.
-_use_bundled_clang=1   # Use bundled clang compiler (needs build). NOTE: if use this option , '_use_clang' need set to 1
+_use_bundled_clang=0   # Use bundled clang compiler (needs build). NOTE: if use this option , '_use_clang' need set to 1
 _use_ccache=1          # Use ccache when build
 _use_pax=0             # Set 1 to change PaX permisions in executables NOTE: only use if use PaX environment
 _use_gtk3=1            # If set 1, then build with GTK3 support, if set 0, then build with GTK2
@@ -22,7 +22,7 @@ pkgname=chromium-dev
 pkgver=53.0.2783.2
 _launcher_ver=5
 pkgrel=1
-pkgdesc="The open-source project behind Google Chrome (Dev Channel)"
+pkgdesc="The open-source project behind Google Chrome Dev Channel"
 arch=('i686' 'x86_64')
 url='http://www.chromium.org'
 license=('BSD')
@@ -89,8 +89,8 @@ makedepends=('libexif'
 
              )
 optdepends=(
-####'chromium-pepper-flash-dev: PPAPI Flash Player (Dev Channel) (64bits only)'
-            'chromium-widevine-dev: Widevine plugin (eg: Netflix) (Dev Channel) (64bits only)'
+####'chromium-pepper-flash-dev: PPAPI Flash Player Dev Channel 64bits only'
+            'chromium-widevine-dev: Widevine plugin eg: Netflix Dev Channel 64bits only'
             #
             'kdebase-kdialog: Needed for file dialogs in KDE4/KF5'
             'kdialog-frameworks-git: Needed for file dialogs in KF5'
@@ -100,7 +100,25 @@ optdepends=(
             'libexif: Need for read EXIF metadata'
             'ttf-font: For some typography'
             )
-source=("https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${pkgver}.tar.xz"
+conflicts=('chromedriver' 'chromium')
+
+allpatches=(
+0200_no_warnings_as_errors.patch
+0300_use_system_clang.patch
+0500_message_center_disabled.patch
+0600_fix_AutofillDialogController.patch
+#0800_small_fixes.patch
+0900_autofill_disabled.patch
+1000_pepper_compile_error.patch
+1100_plugins_disabled.patch
+1200_signin_fix.patch
+1300_background_fix.patch
+#1400_hotword_disabled.patch
+1400_make_linking_work.patch
+)
+
+source=(
+#####"https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${pkgver}.tar.xz"
         "chromium-launcher-${_launcher_ver}.tar.gz::https://github.com/icanrealizeum/chromium-launcher/archive/v${_launcher_ver}.tar.gz"
         'chromium-dev.svg'
         # Patch form Gentoo
@@ -113,12 +131,16 @@ source=("https://commondatastorage.googleapis.com/chromium-browser-official/chro
         'minizip.patch::http://pastebin.com/raw/QCqSDam5'
         # Patch from crbug (chromium bugtracker)
         'chromium-widevine-r1.patch' # https://crbug.com/473866
-        )
-sha1sums=(
-#"$(curl -sL https://gsdview.appspot.com/chromium-browser-official/?marker=chromium-${pkgver}.tar.xz.hashes | awk -v FS='<td>"' -v RS='"</td>' '$0=$2' | head -n1)"
-#          "$(curl -sL https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${pkgver}.tar.xz.hashes | grep sha1 | cut -d " " -f3)"
 
-          'd18f8d96e80be9c31d994cc6362d7d8041c53319'
+        #own patches
+        "${allpatches[@]}"
+        )
+
+##"$(curl -sL https://gsdview.appspot.com/chromium-browser-official/?marker=chromium-${pkgver}.tar.xz.hashes | awk -v FS='<td>"' -v RS='"</td>' '$0=$2' | head -n1)"
+#          "$(curl -sL https://commondatastorage.googleapis.com/chromium-browser-official/chromium-${pkgver}.tar.xz.hashes | grep sha1 | cut -d " " -f3)"
+sha1sums=(
+
+#          'd18f8d96e80be9c31d994cc6362d7d8041c53319'
           '336976cb66bf8df71fc7f2e92aa723891b6efb53'
           # Patch form Gentoo
           '450cd81653499eb50f0f7df1b0d4d1c1620365a5'
@@ -133,6 +155,16 @@ sha1sums=(
           )
 options=('!strip')
 install=chromium-dev.install
+_folder="${startdir}/fetch_gclient_base/checkout_root"
+_srcfolder="${_folder}/src"
+if test "$GYP" = "1"; then
+  _reldir="out/Release" #anything else won't work, even when copied
+else
+  _reldir="out/Default"
+fi
+if test "$inTMPFS" = "1"; then
+  _reldir="/tmp/${_reldir}"
+fi
 
 ################################################
 ## -- Don't touch anything below this line -- ##
@@ -153,7 +185,7 @@ if [ "${CARCH}" = "i686" ]; then
   _pnacl_arch=32
 elif  [ "${CARCH}" = "x86_64" ]; then
   _target_arch=x64
-  _build_pnacl=1
+  _build_pnacl=0  #xchanged
   _pnacl_arch=64
 fi
 
@@ -449,23 +481,198 @@ _use_system=('-Duse_system_expat=1'
              )
 
 ################################################
+getchromiumver() {
+    pushd -- "${_srcfolder}" >/dev/null 2>&1
+    export PATH="${srcdir}/python-path:$PATH"
+    build/util/version.py -f chrome/VERSION -t "@MAJOR@.@MINOR@.@BUILD@.@PATCH@"
+    #FIXME: allow tag --list first and if empty, do the version.py - if the latter fails pkgver won't be changed apparently; that's good because it will have to fail until version.py gets downloaded
+    # tags dont exit with --nohistory: git tag --list --sort="-v:refname" | head -1
+    popd -- >/dev/null 2>&1
+}
+
+pkgver() {
+    cd "${_srcfolder}"
+    printf "%s_r%s.%s" "$(getchromiumver)" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
+    printf "%s_r%s.%s" "$(getchromiumver)" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)" >&2
+}
+
+removestuff() {
+#use like this removestuff <<EOF
+#file1
+#folder2
+#EOF
+#XXX: looks like the above can't contain {} or *   well it can but it won't be expanded (globbing?)
+  if test -z "$1"; then
+    error "you didn't pass a folder name as parameter"
+    exit 1
+  fi
+
+#  read -r -d '' -a templist <&0 || true  #prevent EOF returning exit code 1 and due to set -e fail PKGBUILD!
+
+  msg2 "Removing stuff from folder '$1'"
+  pushd "$1" >/dev/null
+#  echo ${templist[@]}
+#TODO: maybe foreach and make sure they do not contain a first slash! as they are meant to be relative to current folder
+#  cat <<<"$templist" | 
+  xargs --no-run-if-empty --verbose --exit rm -rf -- # <<< "${templist[@]}"  #XXX: stuff is already comming from stdin
+  # ${templist[@]}
+  popd >/dev/null
+#  msg2 "done."
+}
+
+lepatch() {
+#  echo $-
+#  trap -p
+  #since we're inside PKGBUILD we know `set -e` is on, so we don't save its state
+  set +e
+#  set +o pipefail #unaffected by the setting of this
+  #now we need to save/restore the ERR trap or else it gets triggered regardless of the +e setting
+  local restoretrap="`trap -p | grep -E "ERR$"`"
+  #clear ERR trap so we don't fail when patch or grep fails
+  trap -- "" ERR
+#XXX: PKGBUILD has: set -e which is why the following fails when grep doesn't find strings even if you add ` ; true`:
+  msg2 "patch $*" #XXX: $* because $@ adds \n after first param O_o so msg2 doesn't show the rest
+  patch "$@" | grep -B10 -E "(FAILED --|ignored|The next patch|which does not)"
+  local ps=("${PIPESTATUS[@]}") #gets reset after running any statement, so need to save it
+  #local ps="${PIPESTATUS[@]}" #gets reset after running any statement, so need to save it
+#  declare +g -a "ps"
+
+  #restore
+  set -e
+  eval "$restoretrap" 
+#  $restoretrap #yep, unquoted, but doesn't work:
+  #/usr/bin/makepkg:274+ trap -- ''\''error_function' '$pkgfunc'\''' ERR
+  #PKGBUILD: line 274: trap: $pkgfunc': invalid signal specification
+  #actual reported line by trap -p is: trap -- 'error_function $pkgfunc' ERR
+
+#  set -o pipefail
+# dsaodhasiohdoa #should fail - ok that worked!
+  patch_ec="${ps[0]}"
+  grep_ec="${ps[1]}"
+  if test "$grep_ec" -eq 0; then # -o "$patch_ec" -ne 0; then
+    #grepping found strings - this is bad
+    error "patching failed! reapply changes in .rej files above and remake the patch, update patch file and re-execute this. Everything else should be patched because we're using only one patch UNLESS it's the first jinja patch, see the cmd above; For 'Skipping patch.' you just need to ignore those and re-run ./makepatchu and put the updated patch in place"
+    ret=126
+  else
+    if test "$patch_ec" -ne 0; then
+      ret="$patch_ec"
+      error "patch command failed! exit code: $ret"
+    fi
+  fi
+  return $ret
+}
 
 prepare() {
 
   # Set Python2 path
   mkdir -p python-path
-  ln -s /usr/bin/python2 "${srcdir}/python-path/python"
+  ln -s /usr/bin/python2 "${srcdir}/python-path/python" || echo 'probably symlink already existed - ignoring'
   export PATH="${srcdir}/python-path:$PATH"
 
-  cd "chromium-${pkgver}"
+#set|grep -i error
+#exit 1
+  pwd
+  mkdir -p "${_folder}"
+  cd "${_folder}"
 
-  # Fix to save configuration in ~/.config/chromium-dev
-  sed -e "s|'filename': 'chromium-browser'|'filename': 'chromium-dev'|" \
-      -e "s|'confdir': 'chromium'|'confdir': 'chromium-dev'|" \
+# fetch if first time, sync if any other time
+  if test -d "${_srcfolder}" -a -f ".gclient"; then
+#    if [ ! -f ".gclient" ]; then
+#      error ".gclient must exist in `pwd` Something went too wrong! must run fetch instead"
+#      exit 1
+#    fi
+
+#    pushd "${_srcfolder}"
+#    #overwrite all changes, usually made by us in this prepare() function
+#    #let's hope user hasn't made any, they will be lost only when using checkout below (commented out now)
+#    #changes will be stashed
+#    #this is needed for gclient sync to work below
+#
+##fails
+##    "${srcdir}/pythonic" build/linux/unbundle/replace_gyp_files.py "${_use_system[@]}" --undo
+#
+#    for each in ${_use_system[@]}; do
+#      each2="$(echo -n "$each" | sed -e "s|.*_\(.*\)=[0-9]|\1|")"
+#      msg2 "cleaning $each2"
+#      _fold="third_party/${each2}"
+#      if [ -d "$_fold" ]; then
+#        _cleanfolder "${_fold}"
+#      else
+#        warning "ignoring inexistent folder $_fold"
+#      fi
+#    done
+
+#    _cleanfolder "third_party/WebKit" #because of the jinja-r7.patch
+#    _cleanfolder "third_party/webrtc"
+
+#    popd
+
+    msg2 "stashing changes..."
+    gclient recurse --no-progress -- git stash || echo "ignoring failure" # >/dev/null
+    gclient recurse --no-progress -- git stash clear >/dev/null || echo "ignored fails - because it's probably first run with empty src folder"
+    msg2 "sync-ing from the internet"
+    pushd "${_srcfolder}"
+    find . -type f -name '*.sedified' -or -type f -name '*.rej' -or -type f -name '*.cedified' | xargs rm -f -- 
+#TEMP:    find . -type f -name '*_browsertest.*' | xargs rm -f --
+#    TODO: is this really needed?: guess so, but should check updating instructions again sometime
+    if test -d '.git'; then
+      msg2 "git pull (because gclient sync doesn't update src/"
+#      git pull --verbose --tags --depth=1  || ( git checkout master && git pull --tags --depth=1 --verbose )
+#      git pull --progress --verbose || ( git checkout master && git pull --verbose --progress )
+      git pull --verbose || ( git checkout master && git pull --verbose ) || echo "ignoring - because it's probably first run with empty src folder"
+    fi
+    popd
+    #-vvv
+    
+    #"${srcdir}/pythonic"
+#    gclient update --nohooks -v --no-history --jobs 8
+#ok: need to modify .gclient_entries before syncing from internet! but it's part of gclient.py
+#    updgclient_entries
+    #gclient sync -vvv --nohooks --no-history --jobs 1
+    msg2 "gclient sync"
+    #--with_tags  #doesn't fetch tags if repo is already fetched
+    gclient sync --nohooks --no-history --jobs 8  #not using -v , in order to be quiet; ok --shallow is bad, apparently!
+
+#    pwd
+    gnexe="${_srcfolder}/buildtools/linux64/gn"
+    if ! test -f "$gnexe"; then
+      msg2 "gn executable isn't there, so this is probably the first run"
+      msg2 "downloading it now..."
+      download_from_google_storage --no_resume --platform='linux*' --bucket chromium-gn -s src/buildtools/linux64/gn.sha1 | grep -v -- 'CommandException: Invalid command "stat".'
+      #^ this will fail with: "CommandException: Invalid command "stat"."
+      # so using that grep which only returns 1 if that pattern isn't found should work around this and still fail if something else happened - but we can't see it :) unless using that -v to show anything other than that pattern
+    fi
+    if ! test -x "$gnexe"; then
+      chmod a+x "$gnexe"
+    fi
+  else
+    error "unsupported! the src folder '${_srcfolder}' must exist and .gclient file as a sibling too!"
+    exit 22
+#    msg2 "no src folder '${_srcfolder}' fetching..."
+#    msg2 "Note: incomplete fetches should be restarted after you remove the src folder! (or so fetch says: that it doesn't support incomplete fetches)"
+#    fetch --nohooks --no-history chromium
+
+    #XXX: this patch is kinda useless to do after the fetch, because it already fetched everything that the patch is trying to exclude
+#    patch -p1 -i "${srcdir}/$patchavoidfetch"
+#    updgclient_entries
+    # ^ this runs: gclient sync --nohooks --no-history
+    #TODO: now how can I put a  -v  in there?
+    # [0:00:01] remote: Sending approximately 2.72 GiB ...        
+    # with --no-history that is
+  fi
+
+  cd "${_srcfolder}"
+  pwd
+
+#  cd "chromium-${pkgver}"
+
+  # Fix to save configuration in ~/.config/chromium
+      #-e "s|'confdir': 'chromium'|'confdir': 'chromium'|" \
+  sed -e "s|'filename': 'chromium-browser'|'filename': 'chromium'|" \
       -i chrome/chrome_exe.gypi
-  sed -e 's|config_dir.Append("chromium")|config_dir.Append("chromium-dev")|' \
-      -e 's|config_dir.Append("chrome-frame")|config_dir.Append("chrome-frame-dev")|' \
-      -i chrome/common/chrome_paths_linux.cc
+#  sed -e 's|config_dir.Append("chromium")|config_dir.Append("chromium-dev")|' \
+#      -e 's|config_dir.Append("chrome-frame")|config_dir.Append("chrome-frame-dev")|' \
+#      -i chrome/common/chrome_paths_linux.cc
 
   msg2 "Patching the sources"
   # Patch sources from Gentoo
@@ -493,8 +700,11 @@ prepare() {
   popd &> /dev/null
 
   # Make it possible to remove third_party/adobe
-  echo > "${srcdir}/flapper_version.h"
-  _flags+=("-Dflapper_version_h_file=${srcdir}/flapper_version.h")
+#  echo > "${srcdir}/flapper_version.h"
+  _flapfile="${srcdir}/flapper_version.h"
+  [ -f "$_flapfile" ] || echo > "$_flapfile"
+
+  _flags+=( -Dflapper_version_h_file="${_flapfile}" )
 
   # Remove most bundled libraries. Some are still needed.
   msg2 "Removing unnecessary components to save space"
